import { expect, test, type Page } from '@playwright/test'
import initSqlJs from 'sql.js'
import { Deck, Note, Notetype, Package } from 'ankipack'

const PACKAGE_PREVIEW_TIMEOUT = 10_000 // Windows WebKit SQL/WASM preview measured at ~5.2s; Chromium remains sub-second.

async function search(page: Page, query: string) {
  const input = page.getByLabel('Collection search', { exact: true })
  await input.fill(query)
  await expect(input).toHaveValue(query)
  await page.getByRole('button', { name: 'Search', exact: true }).click()
}

async function createNote(page: Page, front: string, back: string) {
  await page.getByRole('button', { name: 'Add note', exact: true }).click()
  await page.getByLabel('Front', { exact: true }).fill(front)
  await page.getByLabel('Back', { exact: true }).fill(back)
  await page.getByRole('button', { name: 'Save note', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Add a note' })).not.toBeVisible()
}

test('browser maintains stable Japanese selections and previews field changes offline', async ({ page, context }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'New deck', exact: true }).click()
  await page.getByLabel('Deck name', { exact: true }).fill('日本語 browser')
  await page.getByRole('button', { name: 'Create deck', exact: true }).click()
  if (test.info().project.use.hasTouch) {
    const deckAction = page.getByRole('button', { name: 'Open 日本語 browser', exact: true })
    await deckAction.scrollIntoViewIfNeeded()
    await page.evaluate(() => window.scrollTo({ top: document.body.scrollHeight, behavior: 'instant' }))
    const actionBox = await deckAction.boundingBox()
    const navigationBox = await page.getByRole('navigation', { name: 'Mobile navigation' }).boundingBox()
    expect(actionBox).not.toBeNull()
    expect(navigationBox).not.toBeNull()
    expect(actionBox!.y + actionBox!.height).toBeLessThanOrEqual(navigationBox!.y + 1)
  }
  await page.getByRole('button', { name: 'Open 日本語 browser', exact: true }).click()
  await createNote(page, '猫', 'cat')
  await createNote(page, '犬', 'dog')
  await expect(page.getByText('Offline shell ready', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Browse', exact: true }).click()
  await search(page, '猫')
  const selected = page.getByRole('checkbox', { name: /^Select card / })
  await expect(selected).toHaveCount(1)
  const identity = await selected.getAttribute('aria-label')
  await selected.check()
  await page.getByRole('button', { name: /^Expression/ }).click()
  await search(page, 'flag:8')
  await expect(page.getByRole('alert')).toContainText('Search error at character 1')
  await expect(page.getByRole('button', { name: '猫', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('checkbox', { name: identity!, exact: true })).toBeChecked()
  await expect(page.getByLabel('Collection search', { exact: true })).toHaveValue('猫')
  await context.setOffline(true)
  try {
    await page.getByRole('button', { name: 'Flag selection', exact: true }).click()
    await page.getByLabel('Card flag', { exact: true }).selectOption('3')
    await page.getByRole('button', { name: 'Apply to selection', exact: true }).click()
    await search(page, 'flag:3')
    await expect(page.getByRole('button', { name: '猫', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Tag selection', exact: true }).click()
    await page.getByLabel('Tags', { exact: true }).fill('jlpt::n5, animals')
    await page.getByRole('button', { name: 'Apply to selection', exact: true }).click()
    await search(page, 'tag:jlpt::*')
    await expect(page.getByRole('button', { name: '猫', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Find / replace / edit', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: 'Find, replace, or edit fields' })
    await dialog.getByLabel('Field', { exact: true }).selectOption({ label: 'Basic · front' })
    await dialog.getByLabel('Find', { exact: true }).fill('猫')
    await dialog.getByLabel('Replacement', { exact: true }).fill('猫ちゃん')
    await dialog.getByRole('button', { name: 'Preview changes', exact: true }).click()
    await expect(dialog.getByRole('heading', { name: '1 notes will change' })).toBeVisible()
    await expect(dialog.getByRole('textbox', { name: 'Before', exact: true })).toHaveValue('猫')
    await expect(dialog.getByRole('textbox', { name: 'After', exact: true })).toHaveValue('猫ちゃん')
    await expect(dialog.getByRole('button', { name: 'Apply field changes' })).toBeDisabled()
    await dialog.getByRole('checkbox', { name: 'I reviewed this preview and want to apply these field changes.' }).check()
    await dialog.getByRole('button', { name: 'Apply field changes' }).click()
    await expect(page.getByRole('button', { name: '猫ちゃん', exact: true })).toBeVisible()
    await expect(page.getByRole('checkbox', { name: identity!, exact: true })).toBeChecked()
    await page.getByLabel('Result view', { exact: true }).selectOption('notes')
    await expect(page.getByRole('table')).toContainText('jlpt::n5, animals')
    await page.getByRole('checkbox', { name: /^Select note / }).check()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= screen.width + 1)).toBe(true)
    await page.screenshot({ path: test.info().outputPath('collection-browser.png'), fullPage: true })
    await page.getByRole('button', { name: 'Delete selection', exact: true }).click()
    const deletion = page.getByRole('dialog', { name: 'Delete selected notes' })
    await expect(deletion).toContainText('1 notes · 1 selected cards · 1 total generated cards')
    await expect(deletion.getByRole('button', { name: 'Delete notes and cards' })).toBeDisabled()
    await deletion.getByRole('checkbox', { name: 'I reviewed the affected counts and want to delete these notes.' }).check()
    await deletion.getByRole('button', { name: 'Delete notes and cards' }).click()
    await expect(deletion).not.toBeVisible()
    await expect(page.getByRole('status').filter({ hasText: 'Applied delete to 1 notes.' })).toBeVisible()
    await search(page, '')
    await expect(page.getByLabel('Collection search', { exact: true })).toHaveValue('')
    await expect(page.getByRole('button', { name: '猫ちゃん', exact: true })).toHaveCount(0)
    await expect(page.getByRole('button', { name: '犬', exact: true })).toBeVisible({ timeout: 15_000 })
  } finally { await context.setOffline(false) }
})

async function largeFixture() {
  const SQL = await initSqlJs({ locateFile: () => './node_modules/sql.js/dist/sql-wasm.wasm' })
  const type = new Notetype({ id: 1_700_000_030_001, name: 'Browser Japanese', fields: [{ name: 'Expression' }, { name: 'Meaning' }], templates: [{ name: 'Recognition', questionFormat: '{{Expression}}', answerFormat: '{{Meaning}}' }] })
  const deck = new Deck({ id: 1_700_000_030_002, name: 'Browser::Japanese' })
  for (let index = 0; index < 72; index++) deck.addNote(new Note({ notetype: type, guid: `browser-${index}`, fields: [index < 2 ? '同じ猫' : index === 71 ? `${'a'.repeat(200)}!` : `日本語${String(index).padStart(3, '0')}`, 'Japanese'], tags: ['fixture'] }))
  const pkg = new Package(); pkg.addDeck(deck)
  return Buffer.from(await pkg.toUint8Array(SQL))
}

test('bulk move and suspension preserve identities and empty reports open affected notes', async ({ page }) => {
  await page.goto('/')
  for (const name of ['Source', 'Destination']) {
    await page.getByRole('button', { name: 'New deck', exact: true }).click()
    await page.getByLabel('Deck name', { exact: true }).fill(name)
    await page.getByRole('button', { name: 'Create deck', exact: true }).click()
  }
  await page.getByRole('button', { name: 'Open Source', exact: true }).click()
  await createNote(page, '待つ', 'wait')
  await createNote(page, '空', 'empty-report')
  await page.getByRole('link', { name: 'Browse', exact: true }).click()
  await search(page, '待つ')
  const selected = page.getByRole('checkbox', { name: /^Select card / })
  const identity = await selected.getAttribute('aria-label')
  await selected.check()
  await page.getByRole('button', { name: 'Move selection', exact: true }).click()
  await page.getByLabel('Destination deck', { exact: true }).selectOption({ label: 'Destination' })
  await page.getByRole('button', { name: 'Apply to selection', exact: true }).click()
  // Apply returns before the async action closes its dialog. Let focus restoration
  // finish before WebKit inserts text into the background collection search.
  await expect(page.getByRole('dialog', { name: 'Move selected notes', exact: true })).toBeHidden()
  await search(page, 'deck:Destination')
  await expect(page.getByRole('checkbox', { name: identity!, exact: true })).toBeChecked()
  await expect(page.getByRole('table').locator('tbody tr')).toHaveCount(1)
  await page.getByRole('button', { name: 'Suspend / restore', exact: true }).click()
  await page.getByRole('button', { name: 'Apply to selection', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Suspend selected cards', exact: true })).toBeHidden()
  await search(page, 'is:suspended')
  await expect(page.getByRole('button', { name: '待つ', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Suspend / restore', exact: true }).click()
  await page.getByLabel('Suspension', { exact: true }).selectOption('restore')
  await page.getByRole('button', { name: 'Apply to selection', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Suspend selected cards', exact: true })).toBeHidden()
  await expect(page.getByRole('table').locator('tbody tr')).toHaveCount(0)
  await search(page, 'deck:Destination')
  await page.reload()
  await expect(page.getByRole('checkbox', { name: identity!, exact: true })).toBeChecked()
  await expect(page.getByRole('table')).toContainText('New')
  await search(page, '空')
  await page.getByRole('button', { name: '空', exact: true }).click()
  const editor = page.getByRole('dialog', { name: 'Edit note fields' })
  await editor.getByLabel('front', { exact: true }).fill('')
  await editor.getByRole('button', { name: 'Save fields', exact: true }).click()
  await expect(editor).not.toBeVisible()
  await search(page, '')
  await page.getByLabel('Report', { exact: true }).selectOption('empty')
  await expect(page.getByRole('table').locator('tbody tr')).toHaveCount(1)
  await page.getByRole('button', { name: 'empty-report', exact: true }).click()
  await expect(editor.getByLabel('front', { exact: true })).toHaveValue('')
  await expect(editor.getByLabel('back', { exact: true })).toHaveValue('empty-report')
  await editor.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= screen.width + 1)).toBe(true)
  await page.screenshot({ path: test.info().outputPath('collection-empty-report.png'), fullPage: true })
})

test('large imported collections page results, report duplicates, and stop expensive regex previews', async ({ page, browserName }) => {
  // The complete 72-note journey measured 28.4s on Windows WebKit, with most
  // time in the durable import. Keep the subsequent editing assertions in budget.
  if (browserName === 'webkit') test.setTimeout(90_000)
  await page.goto('/')
  await page.getByRole('button', { name: 'Import Anki package', exact: true }).click()
  const importer = page.getByRole('dialog', { name: 'Import Anki package' })
  await importer.getByLabel('Anki package', { exact: true }).setInputFiles({ name: 'browser.apkg', mimeType: 'application/octet-stream', buffer: await largeFixture() })
  await expect(importer.getByText('72 notes', { exact: true })).toBeVisible({ timeout: PACKAGE_PREVIEW_TIMEOUT })
  await importer.getByRole('button', { name: 'Import package', exact: true }).click()
  await expect(importer).toBeHidden({ timeout: 45_000 })
  await page.getByRole('link', { name: 'Browse', exact: true }).click()
  await expect(page.getByRole('table').locator('tbody tr')).toHaveCount(50)
  await expect(page.getByText('Page 1 of 2', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Next page', exact: true }).click()
  await expect(page.getByRole('table').locator('tbody tr')).toHaveCount(22)
  await page.getByLabel('Report', { exact: true }).selectOption('duplicates')
  await expect(page.getByRole('table').locator('tbody tr')).toHaveCount(2)
  await expect(page.getByRole('button', { name: '同じ猫', exact: true })).toHaveCount(2)
  await page.getByLabel('Report', { exact: true }).selectOption('all')
  await search(page, 'aaaaaaaaaa')
  await expect(page.getByRole('table').locator('tbody tr')).toHaveCount(1)
  await page.getByRole('checkbox', { name: /^Select card / }).check()
  await page.getByRole('button', { name: 'Find / replace / edit', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Find, replace, or edit fields' })
  await dialog.getByLabel('Field', { exact: true }).selectOption({ label: 'Browser Japanese · Expression' })
  await dialog.getByLabel('Replacement mode', { exact: true }).selectOption('regex')
  await dialog.getByLabel('Find', { exact: true }).fill('^(a+)+$')
  await dialog.getByLabel('Replacement', { exact: true }).fill('changed')
  await dialog.getByRole('button', { name: 'Preview changes', exact: true }).click()
  // Engines can optimize this nonmatching pattern. Both a bounded timeout and
  // an immediate unchanged preview are valid; Chromium exercises the timeout.
  await expect(dialog.getByRole('alert').filter({ hasText: 'This pattern took too long' }).or(dialog.getByRole('heading', { name: '0 notes will change', exact: true }))).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Apply field changes' })).toBeDisabled()
  await dialog.getByLabel('Find', { exact: true }).fill('^(a+)')
  await dialog.getByLabel('Replacement', { exact: true }).fill('日本語$1')
  await dialog.getByRole('button', { name: 'Preview changes', exact: true }).click()
  await expect(dialog.getByRole('textbox', { name: 'After', exact: true })).toHaveValue(`日本語${'a'.repeat(200)}!`)
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('table')).not.toContainText('changed')
})
