import { expect, test } from '@playwright/test'
test('custom practice works offline and returns unchanged home cards after rebuilding and deleting', async ({ page, context }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'New deck', exact: true }).click()
  await page.getByLabel('Deck name', { exact: true }).fill('日本語 focus')
  await page.getByRole('button', { name: 'Create deck', exact: true }).click()
  await page.getByRole('button', { name: 'Open 日本語 focus', exact: true }).click()
  await page.getByRole('button', { name: 'Add note', exact: true }).click()
  await page.getByLabel('Front', { exact: true }).fill('猫')
  await page.getByLabel('Back', { exact: true }).fill('cat')
  await page.getByRole('button', { name: 'Save note', exact: true }).click()
  await expect(page.getByText('Offline shell ready', { exact: true })).toBeVisible()
  await context.setOffline(true)
  await page.getByRole('link', { name: 'Study', exact: true }).click()
  await page.getByLabel('Session name', { exact: true }).fill('猫 practice')
  await page.getByLabel('Session search', { exact: true }).fill('deck:*')
  await page.getByRole('button', { name: 'Preview session', exact: true }).click()
  await expect(page.getByRole('heading', { name: '1 cards selected from 1 matches' })).toBeVisible()
  await page.getByRole('button', { name: 'Create session', exact: true }).click()
  await page.getByRole('link', { name: 'Browse', exact: true }).click()
  await expect(page.getByText('Custom session: 猫 practice (home deck unchanged)')).toBeVisible()
  await page.getByRole('link', { name: 'Study', exact: true }).click()
  await page.getByRole('button', { name: 'Study 猫 practice', exact: true }).click()
  await expect(page.getByText(/Practice: original schedule stays unchanged/)).toBeVisible()
  await page.getByRole('button', { name: 'Show answer', exact: true }).click()
  await page.getByRole('button', { name: 'Good · No schedule change', exact: true }).click()
  await page.getByRole('button', { name: 'Undo last review', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Show answer', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Show answer', exact: true }).click()
  await page.getByRole('button', { name: 'Good · No schedule change', exact: true }).click()
  await page.getByRole('button', { name: 'Back to custom study', exact: true }).click()
  await page.getByRole('button', { name: 'Rebuild 猫 practice', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm rebuild', exact: true }).click()
  await expect(page.getByText('1 temporary cards · 1 available now · 0 answered in this build')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: test.info().outputPath('custom-study.png'), fullPage: true })
  await page.getByRole('button', { name: 'Delete 猫 practice', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm delete', exact: true }).click()
  await page.getByRole('link', { name: 'Decks', exact: true }).click()
  await page.getByRole('button', { name: 'Open 日本語 focus', exact: true }).click()
  await page.getByRole('button', { name: 'Study now', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Show answer', exact: true })).toBeVisible()
})
