import { openCollectionTools } from './collection-tools'
import { expect, test } from '@playwright/test'

async function activate(locator: import('@playwright/test').Locator) {
  await locator.press('Enter')
}

test('keyboard creates, edits, cancels, and deletes a deck with safe focus restoration', async ({ page }) => {
  await page.goto('/')
  const create = page.getByRole('button', { name: 'New deck', exact: true })
  await activate(create)
  const createDialog = page.getByRole('dialog', { name: 'Create a deck' })
  const name = createDialog.getByLabel('Deck name')
  await expect(name).toBeFocused()
  await name.fill('Keyboard deck')
  await activate(name)
  await expect(createDialog).toHaveCount(0)

  await activate(page.getByRole('button', { name: 'Open Keyboard deck', exact: true }))
  const rename = page.getByRole('button', { name: 'Rename deck', exact: true })
  await activate(rename)
  const renameDialog = page.getByRole('dialog', { name: 'Rename deck' })
  const renameInput = renameDialog.getByLabel('Deck name')
  await expect(renameInput).toBeFocused()
  await renameInput.fill('Keyboard deck updated')
  await activate(renameInput)
  await expect(renameDialog).toHaveCount(0)
  await expect(rename).toBeFocused()

  const remove = page.getByRole('button', { name: 'Delete deck', exact: true })
  await activate(remove)
  const deleteDialog = page.getByRole('dialog', { name: 'Delete deck' })
  const cancel = deleteDialog.getByRole('button', { name: 'Cancel' })
  await expect(cancel).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(deleteDialog).toHaveCount(0)
  await expect(remove).toBeFocused()

  await activate(remove)
  const confirmed = page.getByRole('dialog', { name: 'Delete deck' })
  const deleteSubtree = confirmed.getByLabel('Delete this deck and its subtree')
  await deleteSubtree.press('Space')
  await activate(confirmed.getByRole('button', { name: 'Delete deck subtree' }))
  await expect(page.getByRole('button', { name: 'Open Keyboard deck updated', exact: true })).toHaveCount(0)
})

test('keyboard completes review, exports a package, and imports it into a clean collection', async ({ page, browser }, testInfo) => {
  test.setTimeout(90000)
  await page.goto('/')
  const create = page.getByRole('button', { name: 'New deck', exact: true })
  await activate(create)
  const createDialog = page.getByRole('dialog', { name: 'Create a deck' })
  const name = createDialog.getByLabel('Deck name')
  await name.fill('Keyboard export')
  await activate(name)

  await activate(page.getByRole('button', { name: 'Open Keyboard export', exact: true }))
  await activate(page.getByRole('button', { name: 'Add note', exact: true }))
  const noteDialog = page.getByRole('dialog', { name: 'Add a Basic note' })
  await noteDialog.getByLabel('Front', { exact: true }).fill('猫')
  await noteDialog.getByLabel('Back', { exact: true }).fill('cat')
  await activate(noteDialog.getByRole('button', { name: 'Save note', exact: true }))
  await expect(noteDialog).toHaveCount(0)
  const study = page.getByRole('button', { name: 'Study now', exact: true })
  await expect(study).toBeEnabled()
  await activate(study)
  await activate(page.getByRole('button', { name: 'Show answer', exact: true }))
  await activate(page.getByRole('button', { name: /^Good ·/ }))
  await expect(page.getByRole('heading', { name: 'Session complete' })).toBeVisible()
  await activate(page.getByRole('button', { name: 'Back to deck', exact: true }))

  await expect(page.getByText('Offline shell ready', { exact: true })).toBeVisible()
  await openCollectionTools(page)
  await activate(page.getByRole('button', { name: 'Export Anki package', exact: true }))
  const exportDialog = page.getByRole('dialog', { name: 'Export Anki package' })
  await expect(exportDialog.getByRole('button', { name: 'Close export' })).toBeFocused()
  // The imported card should be new and due for the final study step.
  const scheduling = exportDialog.getByRole('checkbox', { name: 'Include scheduling and card suspension' })
  await scheduling.focus()
  await scheduling.press('Space')
  const downloadPromise = page.waitForEvent('download')
  await activate(exportDialog.getByRole('button', { name: 'Download package', exact: true }))
  const download = await downloadPromise
  const file = testInfo.outputPath('keyboard-export.apkg')
  await download.saveAs(file)
  await expect(exportDialog.getByRole('status')).toContainText('1 notes, 1 cards, 1 reviews')

  const cleanContext = await browser.newContext()
  try {
    const clean = await cleanContext.newPage()
    await clean.goto('/')
    const importTrigger = clean.getByRole('button', { name: 'Import Anki package', exact: true })
    await activate(importTrigger)
    const importDialog = clean.getByRole('dialog', { name: 'Import Anki package' })
    const choosePackage = importDialog.getByRole('button', { name: 'Choose package', exact: true })
    await expect(choosePackage).toBeFocused()
    const chooserPromise = clean.waitForEvent('filechooser')
    await activate(choosePackage)
    const chooser = await chooserPromise
    await chooser.setFiles(file)
    await expect(importDialog.getByText('keyboard-export.apkg', { exact: true })).toBeVisible()
    await expect(importDialog.getByRole('status')).toContainText('Reading package', { timeout: 15000 }).catch(() => undefined)
    await expect(importDialog.getByRole('region', { name: 'Package summary' })).toContainText('1 note')
    await activate(importDialog.getByRole('button', { name: 'Import package', exact: true }))
    await expect(importDialog).toHaveCount(0)
    await activate(clean.getByRole('button', { name: 'Open Keyboard export', exact: true }))
    await expect(clean.getByText('猫')).toBeVisible()
  } finally {
    await cleanContext.close()
  }
  expect(browser.contexts()).toEqual([page.context()])
})
