import { expect, test } from '@playwright/test'
import initSqlJs from 'sql.js'
import { readFile } from 'node:fs/promises'
import { navigationPackage } from '../fixtures/secure-navigation'

test('study hides links while authoring retains safe navigation and clean package reimport', async ({ page, context, browser, browserName }) => {
  test.setTimeout(90_000)
  const SQL = await initSqlJs({ locateFile: () => './node_modules/sql.js/dist/sql-wasm.wasm' })
  const bytes = await navigationPackage(SQL)
  const externalRequests: string[] = []
  context.on('request', request => { if (request.url().startsWith('https://example.org/')) externalRequests.push(request.url()) })
  await context.route('https://example.org/**', route => route.fulfill({ status: 200, contentType: 'text/html', body: '<h1>Synthetic external dictionary</h1>' }))
  await page.goto('/')
  await page.getByRole('button', { name: 'Import Anki package', exact: true }).click()
  await page.getByLabel('Anki package', { exact: true }).setInputFiles({ name: 'synthetic-links.apkg', mimeType: 'application/octet-stream', buffer: Buffer.from(bytes) })
  await expect(page.getByRole('button', { name: 'Import package', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Import package', exact: true }).click()
  await page.getByRole('button', { name: 'Open 日本語 links', exact: true }).click()
  await expect(page.getByText('Offline shell ready', { exact: true })).toBeVisible()
  await context.setOffline(true)
  await page.getByRole('button', { name: 'Study now', exact: true }).click()
  const review = page.frameLocator('iframe[title="Review card"]')
  await expect(review.locator('body')).toContainText('猫')
  await expect.poll(() => review.getByRole('img', { name: 'cat.png' }).evaluate(image => (image as HTMLImageElement).naturalWidth)).toBe(1)
  await expect(page.locator('iframe[title="Review card"]')).toHaveAttribute('sandbox', 'allow-same-origin')
  expect(externalRequests).toEqual([])
  await expect(review.locator('a')).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'External card links' })).toHaveCount(0)
  await page.getByRole('button', { name: 'End session', exact: true }).click()
  await page.getByRole('link', { name: 'Note types', exact: true }).click()
  await page.getByRole('button', { name: 'Edit Japanese navigation', exact: true }).click()
  const authoring = page.frameLocator('iframe[title="Card preview"]')
  await expect(authoring.locator('body')).toContainText('猫')
  const cardURL = page.url()
  // Chromium also verifies card-anchor interception; the trusted actions are
  // available for touch/keyboard on both engines independently of frame events.
  if (browserName === 'chromium') await authoring.getByRole('link', { name: 'Dictionary', exact: true }).click()
  else await page.getByRole('region', { name: 'External card links' }).getByRole('button', { name: 'Dictionary · example.org', exact: true }).click()
  const confirmation = page.getByRole('dialog', { name: 'Open an external page' })
  await expect(confirmation).toContainText('https://example.org/dictionary?term=%E7%8C%AB')
  expect(page.url()).toBe(cardURL)
  expect(externalRequests).toEqual([])
  await confirmation.getByRole('button', { name: 'Stay on card', exact: true }).click()
  await page.getByRole('region', { name: 'External card links' }).getByRole('button', { name: 'Reading source · example.org', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(confirmation).toContainText('https://example.org/reading?q=%E6%97%A5%E6%9C%AC%E8%AA%9E')
  await expect(confirmation.getByRole('link', { name: 'Open external page', exact: true })).toHaveAttribute('rel', 'noopener noreferrer')
  await expect.poll(() => confirmation.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: test.info().outputPath('external-destination.png') })
  expect(externalRequests).toEqual([])
  await context.setOffline(false)
  const opened = context.waitForEvent('page')
  await confirmation.getByRole('link', { name: 'Open external page', exact: true }).click()
  const external = await opened
  await expect(external.getByRole('heading', { name: 'Synthetic external dictionary' })).toBeVisible()
  expect(await external.evaluate(() => window.opener === null)).toBe(true)
  expect(externalRequests).toHaveLength(1)
  await external.close()
  await expect(authoring.locator('body')).toContainText('猫')
  expect(page.url()).toBe(cardURL)
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('link', { name: 'Decks', exact: true }).click()
  await page.getByRole('button', { name: 'Open 日本語 links', exact: true }).click()
  await page.getByRole('button', { name: 'Study now', exact: true }).click()
  await page.getByRole('button', { name: 'Show answer', exact: true }).click()
  await expect(review.locator('body')).toContainText('cat · ねこ')
  await page.getByText('More actions', { exact: true }).click()
  await page.getByRole('button', { name: 'Export Anki package', exact: true }).click()
  const exported = page.getByRole('dialog', { name: 'Export Anki package' })
  const downloading = page.waitForEvent('download')
  await exported.getByRole('button', { name: 'Download package', exact: true }).click()
  const output = await (await downloading).path()
  expect(output).not.toBeNull()
  const clean = await browser.newContext()
  try {
    const target = await clean.newPage()
    await target.goto(test.info().project.use.baseURL ?? page.url().split('#')[0])
    await target.getByRole('button', { name: 'Import Anki package', exact: true }).click()
    await target.getByLabel('Anki package', { exact: true }).setInputFiles({ name: 'roundtrip-links.apkg', mimeType: 'application/octet-stream', buffer: await readFile(output!) })
    await target.getByRole('button', { name: 'Import package', exact: true }).click()
    await target.getByRole('button', { name: 'Open 日本語 links', exact: true }).click()
    await target.getByRole('link', { name: 'Note types', exact: true }).click()
    await target.getByRole('button', { name: 'Edit Japanese navigation', exact: true }).click()
    const original = target.frameLocator('iframe[title="Card preview"]')
    await expect(original.getByRole('link', { name: 'Dictionary', exact: true })).toHaveAttribute('data-kiroku-href', 'https://example.org/dictionary?term=%E7%8C%AB')
    await expect(original.getByRole('link', { name: 'Reading source', exact: true })).toHaveAttribute('data-kiroku-href', 'https://example.org/reading?q=%E6%97%A5%E6%9C%AC%E8%AA%9E')
    await target.getByRole('button', { name: 'Cancel', exact: true }).click()
    await target.getByRole('link', { name: 'Decks', exact: true }).click()
    await target.getByRole('button', { name: 'Open 日本語 links', exact: true }).click()
    await target.getByRole('button', { name: 'Study now', exact: true }).click()
    await expect(target.getByRole('region', { name: 'External card links' })).toHaveCount(0)
    const reimport = target.frameLocator('iframe[title="Review card"]')
    await expect(reimport.locator('a')).toHaveCount(0)
    await expect.poll(() => reimport.getByRole('img', { name: 'cat.png' }).evaluate(image => (image as HTMLImageElement).naturalWidth)).toBe(1)
    await target.getByRole('button', { name: 'Show answer', exact: true }).click()
    await expect(reimport.locator('body')).toContainText('cat · ねこ')
  } finally { await clean.close() }
})
