import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, expect, test, vi } from 'vitest'
import { collection } from './collection'
import { CollectionBrowser } from './CollectionBrowser'

vi.mock('./browser-maintenance', async (importOriginal) => {
  const actual = await importOriginal<typeof import('./browser-maintenance')>()
  return { ...actual, previewFieldChanges: vi.fn(async (...args: Parameters<typeof actual.fieldChangePreview>) => actual.fieldChangePreview(...args)) }
})
const deckIds: string[] = []
afterEach(async () => {
  cleanup(); localStorage.removeItem('kiroku.collectionBrowser.v1')
  for (const id of deckIds.splice(0)) await collection.deleteDeck(id, { mode: 'delete-subtree' })
})
async function deck() { const value = await collection.createDeck(`Browser ${crypto.randomUUID()}`); deckIds.push(value.id); return value }
async function search(query: string) {
  fireEvent.change(screen.getByLabelText('Collection search'), { target: { value: query } })
  fireEvent.click(screen.getByRole('button', { name: 'Search' }))
}

test('invalid searches retain valid Japanese results and selection survives sorting and reload', async () => {
  const parent = await deck()
  const cat = await collection.createBasicNote(parent.id, { front: '猫', back: 'cat' })
  await collection.createBasicNote(parent.id, { front: '犬', back: 'dog' })
  const [card] = await collection.cards.where('noteId').equals(cat.id).toArray()
  render(<CollectionBrowser />)
  await screen.findByRole('table')
  await search('猫')
  expect(screen.getByRole('button', { name: '猫' })).toBeVisible()
  expect(screen.queryByRole('button', { name: '犬' })).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('checkbox', { name: `Select card ${card.id}` }))
  fireEvent.click(screen.getByRole('button', { name: /Expression/ }))
  expect(screen.getByRole('checkbox', { name: `Select card ${card.id}` })).toBeChecked()
  await search('flag:8')
  expect(screen.getByRole('alert')).toHaveTextContent('character 1')
  expect(screen.getByRole('alert')).toHaveTextContent('last valid search: 猫')
  expect(screen.getByRole('button', { name: '猫' })).toBeVisible()
  await waitFor(() => expect(localStorage.getItem('kiroku.collectionBrowser.v1')).toContain(card.id))
  cleanup(); render(<CollectionBrowser />)
  await screen.findByRole('table')
  expect(screen.getByLabelText('Collection search')).toHaveValue('猫')
  expect(screen.getByRole('checkbox', { name: `Select card ${card.id}` })).toBeChecked()
})

test('large results render only 50 rows and keep selections when navigating pages and note view', async () => {
  const parent = await deck()
  for (let index = 0; index < 70; index++) await collection.createBasicNote(parent.id, { front: `語彙 ${index}`, back: `word ${index}` })
  render(<CollectionBrowser />)
  const table = await screen.findByRole('table')
  expect(within(table).getAllByRole('row')).toHaveLength(51)
  fireEvent.click(screen.getByRole('checkbox', { name: 'Select this page' }))
  expect(screen.getByText('70 cards · 50 selected')).toBeVisible()
  fireEvent.click(screen.getByRole('button', { name: 'Next page' }))
  expect(within(table).getAllByRole('row')).toHaveLength(21)
  expect(screen.getByText('70 cards · 50 selected')).toBeVisible()
  fireEvent.change(screen.getByLabelText('Result view'), { target: { value: 'notes' } })
  expect(screen.getByText('70 notes · 0 selected')).toBeVisible()
  fireEvent.change(screen.getByLabelText('Result view'), { target: { value: 'cards' } })
  expect(screen.getByText('70 cards · 50 selected')).toBeVisible()
})

test('bulk note deletion requires reviewed counts and removes the selected identities', async () => {
  const parent = await deck()
  await collection.createBasicNote(parent.id, { front: '猫', back: 'cat' })
  await collection.createBasicNote(parent.id, { front: '犬', back: 'dog' })
  render(<CollectionBrowser />)
  await screen.findByRole('table')
  fireEvent.click(screen.getByRole('button', { name: 'Select all results' }))
  fireEvent.click(screen.getByRole('button', { name: 'Delete selection' }))
  const dialog = screen.getByRole('dialog', { name: 'Delete selected notes' })
  await waitFor(() => expect(dialog).toHaveTextContent('2 notes · 2 selected cards · 2 total generated cards'))
  const apply = within(dialog).getByRole('button', { name: 'Delete notes and cards' })
  expect(apply).toBeDisabled()
  fireEvent.click(within(dialog).getByRole('checkbox', { name: /I reviewed the affected counts/ }))
  fireEvent.click(apply)
  await screen.findByText('Applied delete to 2 notes.')
  expect(await collection.notes.count()).toBe(0)
  expect(await collection.cards.count()).toBe(0)
})

test('find/replace previews a selected field and preserves card IDs when applied', async () => {
  const parent = await deck()
  await collection.createBasicNote(parent.id, { front: '猫', back: 'cat one' })
  await collection.createBasicNote(parent.id, { front: '猫', back: 'cat two' })
  const ids = (await collection.cards.toArray()).map((card) => card.id).sort()
  render(<CollectionBrowser />)
  await screen.findByRole('table')
  fireEvent.click(screen.getByRole('button', { name: 'Select all results' }))
  fireEvent.click(screen.getByRole('button', { name: 'Find / replace / edit' }))
  const dialog = screen.getByRole('dialog', { name: 'Find, replace, or edit fields' })
  await within(dialog).findByRole('option', { name: 'Basic · front' })
  fireEvent.change(within(dialog).getByLabelText('Field'), { target: { value: JSON.stringify(['basic', 'front']) } })
  fireEvent.change(within(dialog).getByLabelText('Find', { exact: true }), { target: { value: '猫' } })
  fireEvent.change(within(dialog).getByLabelText('Replacement', { exact: true }), { target: { value: '犬' } })
  fireEvent.click(within(dialog).getByRole('button', { name: 'Preview changes' }))
  await within(dialog).findByRole('heading', { name: '2 notes will change' })
  expect(within(dialog).getAllByLabelText('Before')).toHaveLength(2)
  expect(within(dialog).getByRole('button', { name: 'Apply field changes' })).toBeDisabled()
  fireEvent.click(within(dialog).getByRole('checkbox', { name: /I reviewed this preview/ }))
  fireEvent.click(within(dialog).getByRole('button', { name: 'Apply field changes' }))
  await screen.findByText('Updated fields in 2 notes.')
  const notes = await collection.notes.toArray()
  expect(notes.map((note) => note.fields.front)).toEqual(['犬', '犬'])
  expect(notes.map((note) => note.fields.back).sort()).toEqual(['cat one', 'cat two'])
  expect((await collection.cards.toArray()).map((card) => card.id).sort()).toEqual(ids)
})

test('duplicate and empty-card reports expose affected records in the result surface', async () => {
  const parent = await deck()
  const first = await collection.createBasicNote(parent.id, { front: '猫', back: 'cat one' })
  await collection.createBasicNote(parent.id, { front: '猫', back: 'cat two' })
  const empty = await collection.createBasicNote(parent.id, { front: '犬', back: 'dog' })
  await collection.updateNote(empty.id, { front: '', back: 'dog' })
  render(<CollectionBrowser />)
  await screen.findByRole('table')
  fireEvent.change(screen.getByLabelText('Report'), { target: { value: 'duplicates' } })
  expect(screen.getByText('2 cards · 0 selected')).toBeVisible()
  expect(screen.getAllByRole('button', { name: '猫' })).toHaveLength(2)
  fireEvent.change(screen.getByLabelText('Result view'), { target: { value: 'notes' } })
  expect(screen.getByRole('checkbox', { name: `Select note ${first.id}` })).toBeVisible()
  fireEvent.change(screen.getByLabelText('Report'), { target: { value: 'empty' } })
  expect(screen.getByText('1 notes · 0 selected')).toBeVisible()
  expect(screen.getByRole('checkbox', { name: `Select note ${empty.id}` })).toBeVisible()
})
